name: citibike_rides_inference_pipeline

on:
  schedule:
    - cron: "5 * * * *" 
      workflows: ["citibike_rides_features_pipeline"]
      types:
        - completed

  workflow_dispatch: 

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Run new data fetch pipeline and load to hopsworks
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY}}
        run: python -m pipelines.inference_pipeline
